CREATE TABLE "catalog_items" (
	"id" text PRIMARY KEY NOT NULL,
	"name" text NOT NULL,
	"brand" text NOT NULL,
	"category" text NOT NULL,
	"description" text DEFAULT '' NOT NULL,
	"dose_form" text NOT NULL,
	"digital_verified_id" text DEFAULT '' NOT NULL,
	"google_indexed" boolean DEFAULT true NOT NULL,
	"e_commerce_ready" boolean DEFAULT true NOT NULL,
	"rating" real DEFAULT 0 NOT NULL,
	"reviews_count" integer DEFAULT 0 NOT NULL,
	"price_estimate" text DEFAULT '' NOT NULL,
	"availability" text DEFAULT 'In Stock' NOT NULL,
	"image_url" text,
	"image_gradient" text DEFAULT '' NOT NULL,
	"molecular_formula" text DEFAULT '' NOT NULL,
	"bioavailability" text DEFAULT '' NOT NULL,
	"half_life" text DEFAULT '' NOT NULL,
	"salts" text DEFAULT '[]' NOT NULL,
	"sort_order" integer DEFAULT 0 NOT NULL,
	"active" boolean DEFAULT true NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
